name: Output

on:
  push:
     branches: [ main ]
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: checkout repo content
            uses: actions/checkout@v3 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: execute py script # aggregate current data
            run: |
              python -m pip install -r requirements.txt
              python relative-strength.py true false ${{ secrets.API_KEY }}

          # - name: Push RSRATING.csv to TradingView git clone
          #   run: |
          #     git clone https://kitata2:${{ secrets.PAT }}@github.com/kitata/seed_fred6725_rs_rating.git
          #     cp ./output/RSRATING.csv ./seed_fred6725_rs_rating/data
          #     cd seed_fred6725_rs_rating
          #     git config user.name "CI" && git config user.email "ci@github.com"
          #     git add --all
          #     git commit -m "CI RSRATING update" || echo "nothing to commit"
          #     git push || echo "nothing to push"
          
          - name: push to log git
            run: |
              git clone https://kitata2:${{ secrets.PAT }}@github.com/kitata2/rs-log.git
              rm ./rs-log/output/* && cp -a ./output/. ./rs-log/output
              cd rs-log
              git config user.name "CI" && git config user.email "ci@github.com"
              git add --all
              git commit -m "CI output update" || echo "nothing to commit"
              git push || echo "nothing to push"
          - uses: actions/upload-artifact@v2
            with:
              name: rs_stocks.csv
              path: output
